project:
  type: website

website:
  title: "website_testing"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: refs.qmd
        text: Publications

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

