project:
  type: website

website:
  title: "/daniel_daye/"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: home.qmd
      - href: about.qmd
        text: about.qmd
      - href: refs.qmd
        text: refs.qmd
    right:
      - icon: github
        href: https://www.github.com
        
format:
  html:
    theme: flatly
    css: styles.css

editor: 
  mode: source

execute: 
  freeze: auto
  